# Generated by Django 3.0.3 on 2020-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sw', 'Sports Wear'), ('S', 'Shirt'), ('OW', 'Outwear')], default='s', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Shirt'), ('D', 'Danger')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
